module.exports = [
  {
    type: 'sports.offers.offer.chips',
    data: [
      {
        title: 'All Offers',
        data: [
          {
            type: 'sports.propositions.vertical',
            title: 'Penrith Harness Winners Market',
            subTitle: 'J.Callaghan Driving @ Penrith 11/8',
            matchId: 'HOF1108',
            betOption: 'Racing Offers',
            inPlay: false,
            goingInPlay: false,
            startTime: '2022-08-11T08:12:00.000Z',
            displayTime: '2022-08-11T08:12:00.000Z',
            hasVision: false,
            cashOutEligibility: 'Disabled',
            promoAvailable: false,
            marketsCount: 1,
            shortName: 'Penrith Harness Winners',
            message: 'J.Callaghan Driving @ Penrith 11/8',
            allowMulti: false,
            onlineBetting: true,
            phoneBettingOnly: false,
            propositions: [
              {
                id: '147109',
                numberId: 147109,
                number: 147109,
                name: 'Jack Callaghan 2+ winners',
                sortOrder: 1,
                returnWin: 2.9,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
              {
                id: '147110',
                numberId: 147110,
                number: 147110,
                name: 'Jack Callaghan 3+ winners',
                sortOrder: 2,
                returnWin: 13,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
            ],
            navigation: {
              template: 'screen:sport:match',
              discoveryKey: 'bff:sports:match:page',
              params: {
                sportName: 'Todays Offers',
                competitionName: 'Racing Offers',
                matchName: 'Penrith Harness Winners Market',
              },
            },
            isFeatured: false,
            isVenueExclusive: false,
          },
          {
            type: 'sports.propositions.vertical',
            title: 'Ipswich R1xR2 VMO',
            subTitle: 'BR1 #7 / BR2 #1 both to Win',
            matchId: '1RVMOIPSW0',
            betOption: 'Racing Offers',
            inPlay: false,
            goingInPlay: false,
            startTime: '2022-08-17T02:28:00.000Z',
            displayTime: '2022-08-17T02:28:00.000Z',
            hasVision: false,
            cashOutEligibility: 'Disabled',
            promoAvailable: false,
            marketsCount: 1,
            shortName: 'Ipswich R1xR2 VMO',
            message: 'BR1 #7 / BR2 #1 both to Win',
            allowMulti: false,
            onlineBetting: true,
            phoneBettingOnly: false,
            propositions: [
              {
                id: '191221',
                numberId: 191221,
                number: 191221,
                name: 'Spillify/Aban',
                sortOrder: 1,
                returnWin: 3,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
              {
                id: '191222',
                numberId: 191222,
                number: 191222,
                name: 'both horses must start',
                sortOrder: 2,
                returnWin: 1.01,
                returnPlace: 0,
                bettingStatus: 'Suspended',
                isOpen: false,
                allowPlace: false,
              },
            ],
            navigation: {
              template: 'screen:sport:match',
              discoveryKey: 'bff:sports:match:page',
              params: {
                sportName: 'Sports Exotics',
                competitionName: 'Racing Retail Offer',
                matchName: 'Ipswich R1xR2 VMO',
              },
            },
            isFeatured: false,
            isVenueExclusive: true,
          },
          {
            type: 'sports.propositions.vertical',
            title: 'Cranbourne R3xR5 VMO',
            subTitle: 'MR3 #1 / MR5 #3 both to finish Top 3',
            matchId: '1RVMOCRAN',
            betOption: 'Racing Offers',
            inPlay: false,
            goingInPlay: false,
            startTime: '2022-08-17T03:30:00.000Z',
            displayTime: '2022-08-17T03:30:00.000Z',
            hasVision: false,
            cashOutEligibility: 'Disabled',
            promoAvailable: false,
            marketsCount: 1,
            shortName: 'Cranbourne R3xR5 VMO',
            message: 'MR3 #1 / MR5 #3 both to finish Top 3',
            allowMulti: false,
            onlineBetting: true,
            phoneBettingOnly: false,
            propositions: [
              {
                id: '191209',
                numberId: 191209,
                number: 191209,
                name: 'SaturnIsle/Reactivate Top 3',
                sortOrder: 1,
                returnWin: 3.4,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
              {
                id: '191210',
                numberId: 191210,
                number: 191210,
                name: 'both horses must start',
                sortOrder: 2,
                returnWin: 1.01,
                returnPlace: 0,
                bettingStatus: 'Suspended',
                isOpen: false,
                allowPlace: false,
              },
            ],
            navigation: {
              template: 'screen:sport:match',
              discoveryKey: 'bff:sports:match:page',
              params: {
                sportName: 'Sports Exotics',
                competitionName: 'Racing Retail Offer',
                matchName: 'Cranbourne R3xR5 VMO',
              },
            },
            isFeatured: false,
            isVenueExclusive: true,
          },
          {
            type: 'sports.propositions.vertical',
            title: 'Morphettville R6xR7 VMO',
            subTitle: 'AR6#1 / AR7#10 Both run Top3 17/08',
            matchId: '1RVMOMORP0',
            betOption: 'Racing Offers',
            inPlay: false,
            goingInPlay: false,
            startTime: '2022-08-17T06:05:00.000Z',
            displayTime: '2022-08-17T06:05:00.000Z',
            hasVision: false,
            cashOutEligibility: 'Disabled',
            promoAvailable: false,
            marketsCount: 1,
            shortName: 'Morphettville R6xR7 VMO',
            message: 'AR6#1 / AR7#10 Both run Top3 17/08',
            allowMulti: false,
            onlineBetting: true,
            phoneBettingOnly: false,
            propositions: [
              {
                id: '191581',
                numberId: 191581,
                number: 191581,
                name: 'Trumpsta/Lamoree Top3',
                sortOrder: 1,
                returnWin: 3,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
              {
                id: '191582',
                numberId: 191582,
                number: 191582,
                name: 'Both horses must start',
                sortOrder: 2,
                returnWin: 1.01,
                returnPlace: 0,
                bettingStatus: 'Suspended',
                isOpen: false,
                allowPlace: false,
              },
            ],
            navigation: {
              template: 'screen:sport:match',
              discoveryKey: 'bff:sports:match:page',
              params: {
                sportName: 'Sports Exotics',
                competitionName: 'Racing Retail Offer',
                matchName: 'Morphettville R6xR7 VMO',
              },
            },
            isFeatured: false,
            isVenueExclusive: true,
          },
          {
            type: 'sports.propositions.vertical',
            title: 'Canterbury R6xR7 VMO',
            subTitle: 'SR6 #9 / SR7 #2 both to finish Top 3',
            matchId: '1RVMOCANT',
            betOption: 'Racing Offers',
            inPlay: false,
            goingInPlay: false,
            startTime: '2022-08-17T06:15:00.000Z',
            displayTime: '2022-08-17T06:15:00.000Z',
            hasVision: false,
            cashOutEligibility: 'Disabled',
            promoAvailable: false,
            marketsCount: 1,
            shortName: 'Canterbury R6xR7 VMO',
            message: 'SR6 #9 / SR7 #2 both to finish Top 3',
            allowMulti: false,
            onlineBetting: true,
            phoneBettingOnly: false,
            propositions: [
              {
                id: '191201',
                numberId: 191201,
                number: 191201,
                name: 'TwilightAff/FlowerMoon Top 3',
                sortOrder: 1,
                returnWin: 2.4,
                returnPlace: 0,
                bettingStatus: 'Open',
                isOpen: true,
                allowPlace: false,
              },
              {
                id: '191202',
                numberId: 191202,
                number: 191202,
                name: 'both horses must start',
                sortOrder: 2,
                returnWin: 1.01,
                returnPlace: 0,
                bettingStatus: 'Suspended',
                isOpen: false,
                allowPlace: false,
              },
            ],
            navigation: {
              template: 'screen:sport:match',
              discoveryKey: 'bff:sports:match:page',
              params: {
                sportName: 'Sports Exotics',
                competitionName: 'Racing Retail Offer',
                matchName: 'Canterbury R6xR7 VMO',
              },
            },
            isFeatured: false,
            isVenueExclusive: true,
          },
        ],
      },
      {
        title: 'Venue Exclusive Offers',
        filter: {
          key: 'isVenueExclusive',
          value: true,
        },
      },
    ],
  },
];
