module.exports = [
  {
    type: 'sports.propositions.vertical',
    title: 'NRL/Wenty Park Greys',
    subTitle: 'NRL Penr-Melb H2H & SG6 #1 Win 11/8',
    matchId: 'NRLDapto11',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-11T09:50:00.000Z',
    displayTime: '2022-08-11T09:50:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Enabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'NRL/Wenty Park Greys',
    message: 'NRL Penr-Melb H2H & SG6 #1 Win 11/8',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147015',
        numberId: 147015,
        number: 147015,
        name: 'Penrith/Simply Limelight',
        sortOrder: 1,
        returnWin: 5,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Sports Exotics',
        competitionName: 'Featured Offer',
        matchName: 'NRL/Wenty Park Greys',
      },
    },
    isFeatured: true,
    isVenueExclusive: true,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'NRL Thursday Offer',
    subTitle: 'NRL: Penrith v Melbourne 11/8',
    matchId: '6SPO1008',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-11T09:50:00.000Z',
    displayTime: '2022-08-11T09:55:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'NRL Thursday Offer',
    message: 'NRL: Penrith v Melbourne 11/8',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147071',
        numberId: 147071,
        number: 147071,
        name: 'Kikau/Olam 1st/2nd try',
        sortOrder: 1,
        returnWin: 5,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'NRL Thursday Offer',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'Tennis Thursday Offer',
    subTitle: 'ATP Mrl. Kyrgios v DeMinaur',
    matchId: '5SPO1108',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-11T14:00:00.000Z',
    displayTime: '2022-08-11T14:00:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'Tennis Thursday Offer',
    message: 'ATP Mrl. Kyrgios v DeMinaur',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147136',
        numberId: 147136,
        number: 147136,
        name: 'Kyrgios 2-0/No Tiebreak',
        sortOrder: 1,
        returnWin: 3.75,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'Tennis Thursday Offer',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'Tennis Thursday Offer 1',
    subTitle: 'ATP Mon: Kyrgios vs De Minaur',
    matchId: '4SPO1108',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-11T02:00:00.000Z',
    displayTime: '2022-08-11T14:00:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'Tennis Thursday Offer 1',
    message: 'ATP Mon: Kyrgios vs De Minaur',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147131',
        numberId: 147131,
        number: 147131,
        name: 'Kyrgios 2-0/Serve 10+ Aces',
        sortOrder: 1,
        returnWin: 3.25,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'Tennis Thursday Offer 1',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'Soccer Friday Offer 1',
    subTitle: 'CLB: Esudiantes vs Atletico PR',
    matchId: '1SPO1208',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-12T00:30:00.000Z',
    displayTime: '2022-08-12T00:30:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'Soccer Friday Offer 1',
    message: 'CLB: Esudiantes vs Atletico PR',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147315',
        numberId: 147315,
        number: 147315,
        name: 'Estudiantes 2+Gls/Atl 1+Gls',
        sortOrder: 1,
        returnWin: 3.75,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'Soccer Friday Offer 1',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'AFL Friday Offer',
    subTitle: 'AFL: St Kilda v Brisbane 12/8',
    matchId: '3SPO1108',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-11T02:00:00.000Z',
    displayTime: '2022-08-12T09:50:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'AFL Friday Offer 1',
    message: 'AFL: St Kilda v Brisbane 12/8',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147126',
        numberId: 147126,
        number: 147126,
        name: 'Neale/Steele 65+ Disposals',
        sortOrder: 1,
        returnWin: 3.75,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'AFL Friday Offer',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'EPL 22/23 Season Offer',
    subTitle: '22/23 EPL Season Final Top 4 Standings',
    matchId: '2SUM1707',
    betOption: 'Sport Offer',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-13T13:00:00.000Z',
    displayTime: '2022-08-13T13:00:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'EPL 22/23 Season Offer',
    message: '22/23 EPL Season Final Top 4 Standings',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147341',
        numberId: 147341,
        number: 147341,
        name: 'ManCity/Liv/Chels ALL Top 4',
        sortOrder: 1,
        returnWin: 3.5,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
      {
        id: '147342',
        numberId: 147342,
        number: 147342,
        name: 'ManCity/Liverpool/Chelsea',
        sortOrder: 2,
        returnWin: 1.01,
        returnPlace: 0,
        bettingStatus: 'Suspended',
        isOpen: false,
        allowPlace: false,
      },
      {
        id: '147343',
        numberId: 147343,
        number: 147343,
        name: 'All finish in EPL Top 4',
        sortOrder: 3,
        returnWin: 1.01,
        returnPlace: 0,
        bettingStatus: 'Suspended',
        isOpen: false,
        allowPlace: false,
      },
      {
        id: '147344',
        numberId: 147344,
        number: 147344,
        name: 'Max bet $50. 1 per customer',
        sortOrder: 4,
        returnWin: 1.01,
        returnPlace: 0,
        bettingStatus: 'Suspended',
        isOpen: false,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'EPL 22/23 Season Offer',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'EPL Sunday Offer',
    subTitle: 'EPL: Man City v Bournemouth 14/08',
    matchId: 'EPL_Unique',
    betOption: 'Sport Offer',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-13T14:00:00.000Z',
    displayTime: '2022-08-13T14:00:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'EPL Sunday Offrs 14/08',
    message: 'EPL: Man City v Bournemouth 14/08',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '147001',
        numberId: 147001,
        number: 147001,
        name: 'Haaland Goal 1stHalf & MCWin',
        sortOrder: 1,
        returnWin: 2.5,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
      {
        id: '147002',
        numberId: 147002,
        number: 147002,
        name: 'Max bet $50. 1 per customer',
        sortOrder: 2,
        returnWin: 1.01,
        returnPlace: 0,
        bettingStatus: 'Suspended',
        isOpen: false,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Todays Offers',
        competitionName: 'Sports Offers',
        matchName: 'EPL Sunday Offer',
      },
    },
    isFeatured: false,
    isVenueExclusive: false,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'Soccer VMO Wednesday',
    subTitle: 'MLS: Los Angeles FC v DC United 17/08',
    matchId: '1SVM1708',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-17T02:00:00.000Z',
    displayTime: '2022-08-17T02:38:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'Soccer VMO Wednesday',
    message: 'MLS: Los Angeles FC v DC United 17/08',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '191001',
        numberId: 191001,
        number: 191001,
        name: 'LAFC 1-0 or 2-0 at Halftime',
        sortOrder: 1,
        returnWin: 2.5,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Sports Exotics',
        competitionName: 'Sports Retail Offer',
        matchName: 'Soccer VMO Wednesday',
      },
    },
    isFeatured: false,
    isVenueExclusive: true,
  },
  {
    type: 'sports.propositions.vertical',
    title: 'NRL VMO Thursday',
    subTitle: 'NRL: Souths v Penrith',
    matchId: '1SVM1808',
    betOption: 'Sport Offers',
    inPlay: false,
    goingInPlay: false,
    startTime: '2022-08-18T09:55:00.000Z',
    displayTime: '2022-08-18T09:55:00.000Z',
    hasVision: false,
    cashOutEligibility: 'Disabled',
    promoAvailable: false,
    marketsCount: 1,
    shortName: 'NRL VMO Thursday',
    message: 'NRL: Souths v Penrith',
    allowMulti: false,
    onlineBetting: true,
    phoneBettingOnly: false,
    propositions: [
      {
        id: '191037',
        numberId: 191037,
        number: 191037,
        name: 'Turuva 1st, 2nd or Last Try',
        sortOrder: 1,
        returnWin: 4,
        returnPlace: 0,
        bettingStatus: 'Open',
        isOpen: true,
        allowPlace: false,
      },
    ],
    navigation: {
      template: 'screen:sport:match',
      discoveryKey: 'bff:sports:match:page',
      params: {
        sportName: 'Sports Exotics',
        competitionName: 'Sports Retail Offer',
        matchName: 'NRL VMO Thursday',
      },
    },
    isFeatured: false,
    isVenueExclusive: true,
  },
];
